Content Review:
  - any:
      - _data/*
      - _data/**/*
      - public/assets/*
      - public/assets/**/*
Code Review:
  - all:
      - \!_data/*
      - \!_data/**/*
      - \!public/assets/*
      - \!public/assets/**/*
